finding:
    methods: [findItemsByKeywords, findItemsByCategory, findItemsAdvanced, findCompletedItems, findItemsByProduct, findItemsIneBayStores, getHistograms, getSearchKeywordsRecommendation, getVersion]
    parameters:
        - { name: categoryId, value: null, type: optional, valid: {}, deprecated: false, methods: [findItemsByCategory, findItemsAdvanced] }
        - { name: keywords, value: null, type: optional, valid: {}, deprecated: false, methods: [findItemsByKeywords, findItemsAdvanced] }
        - { name: descriptionSearch, value: null, type: optional, valid: {}, deprecated: false, methods: [findItemsAdvanced] }

        - { name: method, value: get, type: required, valid: [get, post], deprecated: false }
        - { name: ebay_url, value: http://svcs.ebay.com/services/search/FindingService/v1, type: required, valid: {}, deprecated: false }
        - { name: OPERATION-NAME, value: null, type: required, valid: [findItemsByKeywords, findItemsByCategory], deprecated: false }
        - { name: SERVICE-VERSION, value: 1.0.0, type: required, valid: {}, deprecated: false }
        - { name: RESPONSE-DATA-FORMAT, value: xml, type: optional, valid: [xml, json], deprecated: false }
        - { name: GLOBAL-ID, value: EBAY-US, type: optional, valid: [EBAY-US, EBAY-ENCA, EBAY-GB, EBAY-AU, EBAY-AT, EBAY-FRBE, EBAY-FR, EBAY-DE, EBAY-MOTOR, EBAY-IT, EBAY-NLBE, EBAY-NL, EBAY-ES, EBAY-CH, EBAY-HK, EBAY-IN, EBAY-IE, EBAY-MY, EBAY-FRCA, EBAY-PH, EBAY-PL, EBAY-SG], deprecated: false}
        - { name: buyerPostalCode, value: null, type: optional, valid: {}, deprecated: false, synonyms: {}}
        - { name: sortOrder, value: null, type: optional, valid: [BestMatch, BidCountFewest, BidCountMost, CountryAscending, CountryDescending, CurrentPriceHighest, DistanceNearest, EndTimeSoonest, PricePlusShippingHighest, PricePlusShippingLowest, StartTimeNewest], deprecated: false}
        - { name: paginationInput, value: null, type: optional, valid: {}, deprecated: false }
        - { name: paginationOutput, value: null, type: optional, valid: {}, deprecated: false }



